# SPDX-FileCopyrightText: 2018-2023 SAP SE or an SAP affiliate company and Cloud Security Client Java contributors
# SPDX-License-Identifier: Apache-2.0
---
sap:
  security:
    services:
      xsuaa[0]:
        xsappname: xsapp!t0815
        uaadomain: localhost
        clientid: sb-clientId!t0815
        clientsecret: pwd
        url: http://localhost
      xsuaa[1]:
        clientid: sb-clientId!t04711

      identity:
        clientid: sb-clientId!t0815
        domains: localhost